RCTRemoteNotificationReceived ---> OSRemoteNotificationReceived
Building this while using `RCTPushNotification` results in the following error:

```
duplicate symbol _RCTRemoteNotificationReceived in:
    /Users/alonso/dev/audience/mobile/ios/DerivedData/Audience/Build/Products/Debug-iphoneos/libRCTOneSignal.a(RCTOneSignal.o)
    /Users/alonso/dev/audience/mobile/ios/DerivedData/Audience/Build/Products/Debug-iphoneos/libRCTPushNotification.a(RCTPushNotificationManager.o)
ld: 1 duplicate symbol for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

Changing this constant's name to not conflict with react-native's solves the problem.